# visor default preset configuration
# Location: ~/.config/visor/config.toml
# Generate: visor --init

[general]
separator = " | "  # Widget separator

[theme]
name = "default"   # default, powerline, gruvbox, nord, gruvbox-powerline, nord-powerline

[[line]]
  [[line.widget]]
  name = "model"

  [[line.widget]]
  name = "context"
  # [line.widget.extra]
  # show_label = "true"
  # show_bar = "true"
  # bar_width = "10"

  [[line.widget]]
  name = "cache_hit"
  # [line.widget.extra]
  # show_label = "true"

  [[line.widget]]
  name = "api_latency"

  [[line.widget]]
  name = "cost"
  # [line.widget.extra]
  # show_label = "false"

  [[line.widget]]
  name = "git"
